const express = require("express")
const validate = require("../middleware/validation")
const upload = require("../middleware/multer")
const {createadmin,adminlogin} = require("../controllers/adminControllers")
const {usercreate, getalluser, edituser, deleteuser, blockUser, paidUser, getPaidUser} = require("../controllers/userControllers")
const { middelware } = require("../middleware/auth")
const {userSchema, loginSchema} = require("../validators/validate")
const {createPhotoSize, getAllPhotos, deletephoto} = require("../controllers/photoSizeControllers")
const { addPark, getAllParks, deletepark, blockPark } = require("../controllers/parkControllers")
const { dashboardStats } = require("../controllers/dashboardControllers")
const { uploadTemplate, getallTemplate, deleteTemplate } = require("../controllers/frameControllers")
const { uploadPicture,getallPicture,deletePicture } = require("../controllers/PictureControllers")
const limiter  = require("../middleware/rateLimiter")


const router = express.Router()
// router.post("/admin-register",createadmin)
router.post("/admin-login",validate(loginSchema),adminlogin, limiter)
router.post("/admin-usercreate",middelware,validate(userSchema),upload.single("avatar"),usercreate)
router.post("/admin-edituser/:id",middelware,edituser)
router.get("/admin-getalluser",middelware,getalluser)
router.delete("/admin-deleteuser/:id",middelware,deleteuser)
router.patch("/admin-blockuser/:id",middelware,blockUser)
router.patch("/admin-paiduser/:id",middelware,paidUser)
router.get("/admin-getallpaiduser/",middelware,getPaidUser)
router.post("/admin-addphoto",middelware,createPhotoSize)
router.get("/admin-getallphoto",middelware,getAllPhotos)
router.delete("/admin-photodelete/:id",middelware,deletephoto)
router.post("/admin-addpark",middelware,addPark)
router.get("/admin-getallpark",middelware,getAllParks)
router.patch("/admin-blockpark/:id",middelware,blockPark)
router.delete("/admin-deletepark/:id",middelware,deletepark)
router.get("/admin-dashboard",middelware,dashboardStats)
router.post("/admin-uploadtemplate",middelware,upload.single("avatar"),uploadTemplate)
router.get("/admin-getalltemplate",middelware,getallTemplate)
router.delete("/admin-deletetemplate/:id",middelware,deleteTemplate)
router.post("/admin-uploadpicture",middelware,upload.single("avatar"),uploadPicture)
router.get("/admin-getallpicture",middelware,getallPicture)
router.delete("/admin-deletepicture/:id",middelware,deletePicture)



module.exports = router